### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by Noahkiq** [Noahkiq/TheButton#1]
- [ ] add command to send button message to a channel
- [ ] log participants who click on the button (reaction)
  - sqlite database?
- [ ] reset button on click
- [ ] update button every few seconds (1 would probs get ratelimited pretty hard. maybe 5? or try something less limited, ie channel topic?) with multithreading
- [ ] self destruct when 0 seconds is reached
